name: social
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  page_transition: ^2.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  flutter_bloc: ^7.0.1
  conditional_builder: ^1.0.2
  convex_bottom_bar: ^3.0.0
  ionicons: ^0.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/images/welcome.jpg
    - assets/images/login2.jpg
    - assets/images/Sign.png
    - assets/images/face.png
    - assets/images/google.png
    - assets/images/linkid.png
    - assets/images/true.png
    - assets/images/false.png
    - assets/images/night.png
    - assets/images/search.png
    - assets/images/chat.png
    - assets/images/chat2.png
    - assets/images/man.jpg
    - assets/images/like.png
    - assets/images/comment.png
  fonts:
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Light.ttf
    - family: Wendy
      fonts:
        - asset: assets/fonts/WendyOne-Regular.ttf
    - family: Amira
      fonts:
        - asset: assets/fonts/ArimaMadurai-Bold.ttf
    - family: Bir
      fonts:
        - asset: assets/fonts/Biryani-Bold.ttf
    - family: Share
      fonts:
        - asset: assets/fonts/Share-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
